// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.0.5

package helloworld

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type HelloHTTPServer interface {
	HelloDemo(context.Context, *HelloDemoRequest) (*HelloDemoReply, error)
}

func RegisterHelloHTTPServer(s *http.Server, srv HelloHTTPServer) {
	r := s.Route("/")
	r.GET("/hello_demo/{name}", _Hello_HelloDemo0_HTTP_Handler(srv))
}

func _Hello_HelloDemo0_HTTP_Handler(srv HelloHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HelloDemoRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.helloworld.Hello/HelloDemo")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.HelloDemo(ctx, req.(*HelloDemoRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HelloDemoReply)
		return ctx.Result(200, reply)
	}
}

type HelloHTTPClient interface {
	HelloDemo(ctx context.Context, req *HelloDemoRequest, opts ...http.CallOption) (rsp *HelloDemoReply, err error)
}

type HelloHTTPClientImpl struct {
	cc *http.Client
}

func NewHelloHTTPClient(client *http.Client) HelloHTTPClient {
	return &HelloHTTPClientImpl{client}
}

func (c *HelloHTTPClientImpl) HelloDemo(ctx context.Context, in *HelloDemoRequest, opts ...http.CallOption) (*HelloDemoReply, error) {
	var out HelloDemoReply
	pattern := "/hello_demo/{name}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/api.helloworld.Hello/HelloDemo"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
