// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.3
// source: api/helloworld/hello.proto

package helloworld

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateHelloRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateHelloRequest) Reset() {
	*x = CreateHelloRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_helloworld_hello_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHelloRequest) ProtoMessage() {}

func (x *CreateHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_hello_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHelloRequest.ProtoReflect.Descriptor instead.
func (*CreateHelloRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_hello_proto_rawDescGZIP(), []int{0}
}

type CreateHelloReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateHelloReply) Reset() {
	*x = CreateHelloReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_helloworld_hello_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateHelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHelloReply) ProtoMessage() {}

func (x *CreateHelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_hello_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHelloReply.ProtoReflect.Descriptor instead.
func (*CreateHelloReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_hello_proto_rawDescGZIP(), []int{1}
}

type UpdateHelloRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateHelloRequest) Reset() {
	*x = UpdateHelloRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_helloworld_hello_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHelloRequest) ProtoMessage() {}

func (x *UpdateHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_hello_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHelloRequest.ProtoReflect.Descriptor instead.
func (*UpdateHelloRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_hello_proto_rawDescGZIP(), []int{2}
}

type UpdateHelloReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateHelloReply) Reset() {
	*x = UpdateHelloReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_helloworld_hello_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateHelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHelloReply) ProtoMessage() {}

func (x *UpdateHelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_hello_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHelloReply.ProtoReflect.Descriptor instead.
func (*UpdateHelloReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_hello_proto_rawDescGZIP(), []int{3}
}

type DeleteHelloRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteHelloRequest) Reset() {
	*x = DeleteHelloRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_helloworld_hello_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHelloRequest) ProtoMessage() {}

func (x *DeleteHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_hello_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHelloRequest.ProtoReflect.Descriptor instead.
func (*DeleteHelloRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_hello_proto_rawDescGZIP(), []int{4}
}

type DeleteHelloReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteHelloReply) Reset() {
	*x = DeleteHelloReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_helloworld_hello_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteHelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHelloReply) ProtoMessage() {}

func (x *DeleteHelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_hello_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHelloReply.ProtoReflect.Descriptor instead.
func (*DeleteHelloReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_hello_proto_rawDescGZIP(), []int{5}
}

type GetHelloRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetHelloRequest) Reset() {
	*x = GetHelloRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_helloworld_hello_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHelloRequest) ProtoMessage() {}

func (x *GetHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_hello_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHelloRequest.ProtoReflect.Descriptor instead.
func (*GetHelloRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_hello_proto_rawDescGZIP(), []int{6}
}

type GetHelloReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetHelloReply) Reset() {
	*x = GetHelloReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_helloworld_hello_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHelloReply) ProtoMessage() {}

func (x *GetHelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_hello_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHelloReply.ProtoReflect.Descriptor instead.
func (*GetHelloReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_hello_proto_rawDescGZIP(), []int{7}
}

type ListHelloRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListHelloRequest) Reset() {
	*x = ListHelloRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_helloworld_hello_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHelloRequest) ProtoMessage() {}

func (x *ListHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_hello_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHelloRequest.ProtoReflect.Descriptor instead.
func (*ListHelloRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_hello_proto_rawDescGZIP(), []int{8}
}

type ListHelloReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListHelloReply) Reset() {
	*x = ListHelloReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_helloworld_hello_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListHelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHelloReply) ProtoMessage() {}

func (x *ListHelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_hello_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHelloReply.ProtoReflect.Descriptor instead.
func (*ListHelloReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_hello_proto_rawDescGZIP(), []int{9}
}

type HelloDemoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *HelloDemoRequest) Reset() {
	*x = HelloDemoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_helloworld_hello_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloDemoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloDemoRequest) ProtoMessage() {}

func (x *HelloDemoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_hello_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloDemoRequest.ProtoReflect.Descriptor instead.
func (*HelloDemoRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_hello_proto_rawDescGZIP(), []int{10}
}

func (x *HelloDemoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HelloDemoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *HelloDemoReply) Reset() {
	*x = HelloDemoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_helloworld_hello_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloDemoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloDemoReply) ProtoMessage() {}

func (x *HelloDemoReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_hello_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloDemoReply.ProtoReflect.Descriptor instead.
func (*HelloDemoReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_hello_proto_rawDescGZIP(), []int{11}
}

func (x *HelloDemoReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_helloworld_hello_proto protoreflect.FileDescriptor

var file_api_helloworld_hello_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x61, 0x70, 0x69, 0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64,
	0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x61, 0x70,
	0x69, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x1a, 0x1c, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x14, 0x0a, 0x12, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x12, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x14, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x65,
	0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x12, 0x0a, 0x10, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x14,
	0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x12, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x65,
	0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x11, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x48,
	0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0f, 0x0a, 0x0d, 0x47,
	0x65, 0x74, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x12, 0x0a, 0x10,
	0x4c, 0x69, 0x73, 0x74, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x10, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x26, 0x0a, 0x10, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x44, 0x65, 0x6d, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2a, 0x0a, 0x0e, 0x48, 0x65,
	0x6c, 0x6c, 0x6f, 0x44, 0x65, 0x6d, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x8c, 0x04, 0x0a, 0x05, 0x48, 0x65, 0x6c, 0x6c, 0x6f,
	0x12, 0x53, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12,
	0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77,
	0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x65, 0x6c, 0x6c, 0x6f,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x53, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48,
	0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f,
	0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x65, 0x6c, 0x6c,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x68,
	0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x53, 0x0a, 0x0b, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x4a, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x1f, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x47, 0x65, 0x74,
	0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x47, 0x65,
	0x74, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4d, 0x0a, 0x09, 0x4c,
	0x69, 0x73, 0x74, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x68,
	0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x65,
	0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x69, 0x0a, 0x09, 0x48, 0x65,
	0x6c, 0x6c, 0x6f, 0x44, 0x65, 0x6d, 0x6f, 0x12, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x68, 0x65,
	0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x44, 0x65,
	0x6d, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f,
	0x44, 0x65, 0x6d, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1a, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x14, 0x12, 0x12, 0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x5f, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x7b,
	0x6e, 0x61, 0x6d, 0x65, 0x7d, 0x42, 0x39, 0x0a, 0x0e, 0x61, 0x70, 0x69, 0x2e, 0x68, 0x65, 0x6c,
	0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x50, 0x01, 0x5a, 0x25, 0x64, 0x65, 0x6d, 0x6f, 0x5f,
	0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f,
	0x77, 0x6f, 0x72, 0x6c, 0x64, 0x3b, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_helloworld_hello_proto_rawDescOnce sync.Once
	file_api_helloworld_hello_proto_rawDescData = file_api_helloworld_hello_proto_rawDesc
)

func file_api_helloworld_hello_proto_rawDescGZIP() []byte {
	file_api_helloworld_hello_proto_rawDescOnce.Do(func() {
		file_api_helloworld_hello_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_helloworld_hello_proto_rawDescData)
	})
	return file_api_helloworld_hello_proto_rawDescData
}

var file_api_helloworld_hello_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_helloworld_hello_proto_goTypes = []interface{}{
	(*CreateHelloRequest)(nil), // 0: api.helloworld.CreateHelloRequest
	(*CreateHelloReply)(nil),   // 1: api.helloworld.CreateHelloReply
	(*UpdateHelloRequest)(nil), // 2: api.helloworld.UpdateHelloRequest
	(*UpdateHelloReply)(nil),   // 3: api.helloworld.UpdateHelloReply
	(*DeleteHelloRequest)(nil), // 4: api.helloworld.DeleteHelloRequest
	(*DeleteHelloReply)(nil),   // 5: api.helloworld.DeleteHelloReply
	(*GetHelloRequest)(nil),    // 6: api.helloworld.GetHelloRequest
	(*GetHelloReply)(nil),      // 7: api.helloworld.GetHelloReply
	(*ListHelloRequest)(nil),   // 8: api.helloworld.ListHelloRequest
	(*ListHelloReply)(nil),     // 9: api.helloworld.ListHelloReply
	(*HelloDemoRequest)(nil),   // 10: api.helloworld.HelloDemoRequest
	(*HelloDemoReply)(nil),     // 11: api.helloworld.HelloDemoReply
}
var file_api_helloworld_hello_proto_depIdxs = []int32{
	0,  // 0: api.helloworld.Hello.CreateHello:input_type -> api.helloworld.CreateHelloRequest
	2,  // 1: api.helloworld.Hello.UpdateHello:input_type -> api.helloworld.UpdateHelloRequest
	4,  // 2: api.helloworld.Hello.DeleteHello:input_type -> api.helloworld.DeleteHelloRequest
	6,  // 3: api.helloworld.Hello.GetHello:input_type -> api.helloworld.GetHelloRequest
	8,  // 4: api.helloworld.Hello.ListHello:input_type -> api.helloworld.ListHelloRequest
	10, // 5: api.helloworld.Hello.HelloDemo:input_type -> api.helloworld.HelloDemoRequest
	1,  // 6: api.helloworld.Hello.CreateHello:output_type -> api.helloworld.CreateHelloReply
	3,  // 7: api.helloworld.Hello.UpdateHello:output_type -> api.helloworld.UpdateHelloReply
	5,  // 8: api.helloworld.Hello.DeleteHello:output_type -> api.helloworld.DeleteHelloReply
	7,  // 9: api.helloworld.Hello.GetHello:output_type -> api.helloworld.GetHelloReply
	9,  // 10: api.helloworld.Hello.ListHello:output_type -> api.helloworld.ListHelloReply
	11, // 11: api.helloworld.Hello.HelloDemo:output_type -> api.helloworld.HelloDemoReply
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_helloworld_hello_proto_init() }
func file_api_helloworld_hello_proto_init() {
	if File_api_helloworld_hello_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_helloworld_hello_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateHelloRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_helloworld_hello_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateHelloReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_helloworld_hello_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateHelloRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_helloworld_hello_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateHelloReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_helloworld_hello_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteHelloRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_helloworld_hello_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteHelloReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_helloworld_hello_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHelloRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_helloworld_hello_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHelloReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_helloworld_hello_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListHelloRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_helloworld_hello_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListHelloReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_helloworld_hello_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloDemoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_helloworld_hello_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloDemoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_helloworld_hello_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_helloworld_hello_proto_goTypes,
		DependencyIndexes: file_api_helloworld_hello_proto_depIdxs,
		MessageInfos:      file_api_helloworld_hello_proto_msgTypes,
	}.Build()
	File_api_helloworld_hello_proto = out.File
	file_api_helloworld_hello_proto_rawDesc = nil
	file_api_helloworld_hello_proto_goTypes = nil
	file_api_helloworld_hello_proto_depIdxs = nil
}
